version: "3.3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"

  gitapi:
    build: .
    environment:
      DB_PASSWORD: "${DB_PASSWORD}"
    depends_on:
      - postgres
    ports:
      - "3000:3000"
