name: coverage

on:
  push:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16

      - name: Clojure
        uses: DeLaGuardo/setup-clojure@3.2
        with:
          lein: 2.9.4

      - name: Coverage
        run: lein with-profile +cloverage cloverage
        shell: bash

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/coverage
